#!/usr/bin/env bash
# Check if java is installed
if ! command -v java &> /dev/null; then
    echo 'Please install java before running this app!'
    exit 1
fi

# Get the script directory
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ ! -f "$script_dir/build/libs/Sort.jar" ]; then
    # Run gradle tasks (assuming gradlew is executable)
    "$script_dir/gradlew" clean build
fi

# Run the Sort.jar with all arguments passed to the script
java -jar "$script_dir/build/libs/Sort.jar" "$@"
